MainWidget:

<MainWidget>:
    canvas.before:
        Color:
            rgba: 1,1,1, 1
        Rectangle:
            pos: self.pos
            size: self.size
        AsyncImage:
            id: theater_name
            pos_hint: {'x': 0, 'top': 1}
            size_hint: None, 5/32
            width: root.width - 10
            #height: (root.height - 10) * 5/32
            source: root.twilight
            allow_stretch: True
            opacity: 1
            keep_ratio: True
